### ISSUE TITLE
Installation: docker-compose up not working

### ISSUE THREAD

**Issue by segysego** [openfoodfacts/robotoff#139]
**Describe the bug**
I just tried to launch robotoff in local using the `docker-compose up` command (without -d option to see the logs).
I found that the elasticsearch_1 and tf_serving_1 containers crash continuously in a loop.

**To Reproduce**
1. install Docker version 19.03.8, build afacb8b7f0
2. install docker-compose version 1.25.4, build 8d51620a
3. clone the project
4. launch `docker-compose up`

**Expected behavior**
I expected to see logs showing everything gets up and running

**Screenshots**
![Capture d’écran de 2020-04-15 21-08-14](https://user-images.githubusercontent.com/22233204/79378278-569c6e80-7f5d-11ea-9014-402471cb338b.png)

**Additional context**
Error log from tf_serving: tf_serving_1     | 2020-04-15 18:58:52.663363: F tensorflow_serving/model_servers/server.cc:97] Non-OK-status: ParseProtoTextFile(file, &proto) status: Not found: /models/models.config; No such file or directory

Error log from elasticsearch: elasticsearch_1  | ERROR: [1] bootstrap checks failed
elasticsearch_1  | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]

**Comment by raphael0202** [comment]
The issue with elasticsearch is known, you have to increase vm.max_map_count on your system: https://stackoverflow.com/questions/51445846/elasticsearch-max-virtual-memory-areas-vm-max-map-count-65530-is-too-low-inc
This should be added to the README, my mistake.

The second error is from tensorflow-serving, because the model config file is not present. The models are not part of the repository, but are stored directly on the server. You don't have to launch tensorflow-serving for the other services to work well, as long as you don't call the /images/predict endpoint.

**Comment by raphael0202** [comment]
I've added the tensorflow model config file, which should prevent the TF serving error (24fc0ae52d9d36b1d6b71894284735cd72649686), and a warning in the README about this Elasticsearch config (609a36a9243586afef869f559f90f7adaede31ab). Feel free to open the bug if you still experience issues.

**Comment by segysego** [comment]
Thank you very much @raphael0202 :), I wil retry.

**Comment by segysego** [comment]
I just retried and it seems to be working now :) although I get the following error every second:

```
tf_serving_1     | 2020-04-26 18:40:53.554446: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path /models/nutriscore/ for servable nutriscore
```

I think this is link to the fact that I never downloaded any model.

**Comment by raphael0202** [comment]
Indeed! Unless you're working on the model it should however be ok
