### ISSUE TITLE
Add support to flashtext USDA packager codes

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#466]
### What

- https://github.com/openfoodfacts/openfoodfacts-server/issues/3704
- The list is available in the XLSX, in the second tab: "Est. 23466", but there are probably variants we'll find on OCRs.
<img src="https://user-images.githubusercontent.com/1689815/85283489-bcd9cc00-b48d-11ea-8057-1e074d2a8fc6.png" height="400px">
<img src="https://world.openfoodfacts.org/images/products/089/310/100/1041/front_en.5.400.jpg" height="400px">

### Part of
- #374 
- [US support](https://github.com/openfoodfacts/openfoodfacts-server/issues/5689)

**Comment by GabrielBeFr** [comment]
I pushed my modifications to solve this problem about a week ago but, after executing the ocr prediction on a dump of ocr results, I realised the amount of false positive was way too high. I will change my REGEX to make the search more precise. I will also put the Automatic processing to False in order to avoid any problem if  we were to put this new feature in prod. 
@teolemon what do you think of limitating the search of USDA packager codes to US products ? Do you know if non-US product can also have USDA packager codes ?
