### ISSUE TITLE
Too many Nutri-Score grade bad detection

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/robotoff#499]
Robotoff's Nutri-Score grade detection (in #nutriscore-alert channel on Slack) produce too many false positive.

7 false results for 10 products.

These results are automatically applied.

**Comment by kulizhsy** [comment]
The plan is to disable the automatic application of the `nutri-score` model, which is the model that is responsible for grade-level Nutri-Score detection.

We have a second model, the `universal-logo-detector` which detects the overall presence of a Nutri-Score label, which should be safe to leave as-is since it doesn't try to predict the individual grades.
