### ISSUE TITLE
Should container-deploy-ml be triggered by master and deploy-*

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/robotoff#565]
robotoff-ml is a production instance which is also used by preprod.

Actual definition of container-deploy-ml makes it being deployed on each preprod release.
Something is wrong there, and there is the risk of messing up robotoff prod !

So:
* either we deploy robotoff-ml only on v*.*.* tags (like prod)
* or we should have two distinct instances (one for preprod, one for prod)

**Comment by alexgarel** [comment]
@mithridatea @CharlesNepote @ocervell your comments are welcome

**Comment by alexgarel** [comment]
We could also avoid reloading models when there is no need of it, by putting a ML_VERSION file and running workflow only if this file changes.

**Comment by mithridatea** [comment]
We rarely ship new ML models, so the simplest way to me is to trigger the deployment of TF Serving manually, when a new tag is added for instance (something like `tf-serving-deploy-*`).
About preprod/prod,  it would be best to have two distinct environments if we can afford it, so that we don't mess up production when testing a model on preprod (even if this case shouldn't occur, as we should always deploy a new TF Serving model version when updating a model).

**Comment by alexgarel** [comment]
The idea of a new tag for deploying is simple and effective.

For prod / preprod split, I think we can afford it, for we gain on old robotoff instances.

**Comment by raphael0202** [comment]
Models are now synced only when adding a version tag `v*.*.*` or when adding a tag `model-deploy*` (see #977)
Adding Triton to docker production server is still required, and can be done when we have enough RAM on this instance.

**Comment by raphael0202** [comment]
TF Serving and Triton are now deployed in prod. robotoff-org (prod) uses these prod containers.
