### ISSUE TITLE
Retro apply category prediction on existing products

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/robotoff#636]
We made category prediction applies automatically if they are good enough, see #552

It's in production and it's applied to newly created / updated products.

Now we want to use this prediction for all products we have in database.

**Comment by alexgarel** [comment]
@CharlesNepote @teolemon I used [this gist](https://gist.github.com/alexgarel/0098218b04e2afb97d33d6f40e485063) to produce this control file:  [auto-cat2.ods](https://drop.picasoft.net/r/Xs_VeLDy#rIcREWSdQIr9ofHi2IPdD3/xMBOs3X4wNSIlh9oWmFg=)

**Comment by alexgarel** [comment]
Some thing that maybe wrong (wandering about):

- line 3556: [0793618106089](https://world.openfoodfacts.org/product/0793618106089) categorized harissa-sauces but this is peanut butter (product name is misleading)
- line 3490: [0772065383267](https://world.openfoodfacts.org/product/0772065383267) classified soup a soup powder (is it correct)
- line 10285: [7622210942593](https://world.openfoodfacts.org/product/7622210942593) classified as egg, while they are chocolate eggs !

This is from a verification of about 100 / 200 items.

**Comment by CharlesNepote** [comment]
I had a look at 100 random products with automatic application of categories. I'm a bit sceptical.
* https://world.openfoodfacts.org/product/8032568610508/pecorino => cheese instead of wine
* This one seems also wrong: https://world.openfoodfacts.org/product/8032454071260/sotto-le-stelle
* This one also: https://world.openfoodfacts.org/product/8032551702067/biscottone
* https://world.openfoodfacts.org/product/8032611854781/hydro-fuel has a wrong category
* https://world.openfoodfacts.org/product/8032628471049/origano => condiments??
* https://world.openfoodfacts.org/product/8032644301313/link-skin-dentro has a wrong category
* https://world.openfoodfacts.org/product/8032841431868/finest-veylon-tea is an issue

With a total of 7 issues for 100 products. I think it's really too high. If we intend to apply this on ~1,000,000 products or more, it will lead to 70,000 issues, which is huge.

Many products also have a very generic (too generic?) category: eg. https://world.openfoodfacts.org/product/8031183000237/pesto-mediterraneo => en:groceries

I even think we should stop the automatic application of categories for the new products, as we are doing now.

**Comment by alexgarel** [comment]
So current position is:
- we should remove auto processing if we only have title
- we should auto process if we have ingredients, if predictions are good enough.

Here is a new PDF for products with ingredients, so that we can validate if we keep automation for products with ingredients.

**Comment by alexgarel** [comment]
Rewied page 1 to 3 ~ 40 products

Not sure it is ok, my doubts:
- [0021130006328](https://world.openfoodfacts.org/product/0021130006328/distilled-white-vinegar) distilled white vinegar classified as "sauce"
- [0024000223467](https://world.openfoodfacts.org/product/0024000223467/fruit-refreshers-snack-cups-del-monte) - fruit water classified as  en:snacks / en:confectioneries

**Comment by teolemon** [comment]
Collaborative version of auto-cat3.pdf: https://drive.google.com/file/d/1L7MA--lpiiXF7tHWOvrYodEuv6gr_gi_/view?usp=sharing

**Comment by alexgarel** [comment]
@teolemon and @CharlesNepote can we take a decision on this, so that it makes it to next delivery ?

**Comment by CharlesNepote** [comment]
My results for the moment:
* 75 products checked (p. 12 to 16)
* about 10 issues

More than 10% issues is far too much, IMHO.
I can try to check 100 or 200 products, but I don't think the proportion of issues will lower to less than 5%.

I think what is to do next is probably to check if we can filter some of the most common issues. For example, there seem to be many issues related to groceries, beverages/non-beverages, sauces.

**Comment by alexgarel** [comment]
Ok, so let's switch it off for the moment. Do we agree @teolemon and @CharlesNepote  ?

**Comment by alexgarel** [comment]
"switch off"  the auto-application, I mean, of course, prediction and insight remains !
I may as well run the model for old products, to have better insights to propose to our users to products already in the database.

**Comment by CharlesNepote** [comment]
Yes I think it's better to switch off the auto-application.

Is it possible to know how many times people validate or not the prediction from this model? Could the users' validations enhance the model?

**Comment by alexgarel** [comment]
> Is it possible to know how many times people validate or not the prediction from this model? Could the users' validations enhance the model?

All this is stored in the database.

**Comment by alexgarel** [comment]
I disabled the auto application of categories - see #652 and released to prod.

Now we can re-compute prediction for products where we don't have recent one, but without au-application.

**Comment by alexgarel** [comment]
We must have a better model before applying automatically.
